export const DEFAULT_LINKED_LIST_THRESHOLD = 10;
export const CHUNK_SIZE = 850;
export const DIRECT_METADATA_MAX_BYTES = 900;
export const DEFAULT_WRITE_FEE_RECEIVER =
    "EWNSTD8tikwqHMcRNuuNbZrnYJUiJdKq9UXLXSEU4wZ1";
export const DEFAULT_IQ_MINT =
    "3uXACfojUrya7VH51jVC1DCHq3uzK4A7g469Q954LABS";
